### ISSUE TITLE
Shop sidebar

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/Ares#12]
- [x] As a shop owner, it would be nice to have the ability to create a sidebar specific for the shop. This way I can add widgets such as cart, product categories, price filter etc..
The shop sidebar would be it's own widget area, separate from the theme main sidebar
- [x] It would also be great to be able to toggle the shop sidebar in both the shop page and in the single product page in the theme customizer Shop Layout and Single Product Layout. if woocommerce is not active, these sections would not show up in customizer.
- [x] See image1 below

*image1*
![image](https://user-images.githubusercontent.com/3696057/32606853-d908c936-c524-11e7-8764-7afe67ce1bcb.png)

**Comment by zackmitchell** [comment]
Actioned
