### ISSUE TITLE
Cart icon 

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/Ares#13]
- [x] Add a cart icon if woo is active 
- [x] clicking the icon, show cart items within, and show button to go to cart

**Comment by zackmitchell** [comment]
You can ignore the revert (c6dac70) then revert back - It was just due to me hitting enter on the commit before finishing my commit message, then attempting to change the commit message.

Everything was actioned in 7965d7e and the most recent commit, f8f0c13 is up-to-date.
