### ISSUE TITLE
Investigate image size on woo single product

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/Ares#14]
![image](https://user-images.githubusercontent.com/3696057/32607862-470635e2-c528-11e7-9ced-7e2e35552122.png)

**Comment by zackmitchell** [comment]
![screen shot 2017-11-09 at 8 57 45 am](https://user-images.githubusercontent.com/12202533/32608988-193be66c-c52c-11e7-8506-16d4dee70e88.png)
